[tool.poetry]
name = "apple-data"
version = "1.0.365"
description = "Static data from https://docs.hackdiffe.rent"
readme = "README.md"

authors = ["Rick Mark <rickmark@outlook.com>"]

include = ['share/**/*']