# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish Package - Node / NPM

on:
  push:
    branches: [ main ]

jobs:
  ci-build-node:
    uses: hack-different/apple-knowledge/.github/workflows/build-node.yml@main

  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: ci-build-node
    environment: node-push

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: _packages/node/yarn.lock
          registry-url: https://registry.npmjs.org/

      - name: Download Node Package Artifacts
        uses: actions/download-artifact@v3
        with:
          name: package-node
          path: dist

      - name: Publish to NPM Registry
        run: yarn publish dist/
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
